### ISSUE TITLE
我放到了一个可以隐藏的布局中，结果隐藏布局后该控件会残留图像

### ISSUE THREAD

**Issue by dongweiq** [HeZaiJin/AnimatedRecordingView#3]
将AnimatedRecordingView放到了一个RelativeLayout中，是一个语音的对话框，用这个控件来显示语音的状态，不需要语音后设置RelativeLayout为gone，Relative虽然隐藏了，但AnimatedRecordingView却残留在了屏幕上，除非退出当前界面，请问这个有办法隐藏吗？

**Comment by HeZaiJin** [comment]
直接设置AnimatedRecordingView gone 可以吗？

**Comment by dongweiq** [comment]
我试试啊

**Comment by dongweiq** [comment]
直接设置就可以隐藏了，谢谢，下次就需要手动的设置与对话框一起隐藏和显示了

**Comment by HeZaiJin** [comment]
好的，这块详细是什么原因我也不清楚。暂时先close了。
